//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appGestion_conge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employer()
        {
            this.conges = new HashSet<conge>();
        }
    
        public int noemployer { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> datenaissance { get; set; }
        public string grade { get; set; }
        public Nullable<int> telephone { get; set;}
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        public string username { get; set; }
        public string motdepasse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conge> conges { get; set; }
    }
}
